### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by TheColourIndigo** [Sumwunn/SSGSPlugin_FO4#3]
Is there any possible way for someone without coding experience to keep this current? I had it working for a day or so in October, but it hasn't worked since. And I loved having this working.

**Comment by Sumwunn** [comment]
Lots of distractions as of late.

I will update this today I promise! :)

**Comment by TheColourIndigo** [comment]
No worries! I'd help if I knew what I was doing. XD

On Feb 19, 2018 10:11 AM, Sumwunn <notifications@github.com> wrote:

Lots of distractions as of late.

I will update this today I promise! :)

**Comment by Sumwunn** [comment]
Updated!

Enjoy. :)

**Comment by TheColourIndigo** [comment]
Hey thanks. I wasn't expecting such a nice and quick response! I truly appreciate this plugin.
